import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { validateAuthorityReviewBundle,validateAuthorityReviewCandidate } from '../scripts/lib/authority-review.mjs';
import { loadTrust,verifyEnvelope } from '../scripts/lib/validate.mjs';

const root=process.cwd();const fixtures=path.join(root,'fixtures');const registry=JSON.parse(await readFile(path.join(fixtures,'registry.json'),'utf8'));const entry=registry.authorityReviews[0];const envelope=JSON.parse(await readFile(path.join(fixtures,entry.envelopeFile),'utf8'));const archiveBytes=await readFile(path.join(fixtures,entry.archiveFile));const lock=JSON.parse(await readFile(path.join(root,'contracts/authority-review-lock.json'),'utf8'));const trust=await loadTrust(fixtures);const bundle=validateAuthorityReviewBundle(envelope,archiveBytes,lock,verifyEnvelope(envelope,trust));
const packet=bundle.archive.packets[0].value;const item=packet.source_binding;const binding={anchor_id:item.anchor_id,document_id:item.document_id,document_url:item.document_url,source_ids:item.source_ids,locked_source_digest:item.locked_source_digest,inventory_tool_digest:item.inventory_tool_digest,review_queue_tool_digest:item.review_queue_tool_digest,locator:item.locator,locator_kind:item.locator_kind,context_start:item.context_start,context_end:item.context_end,context_unit:item.context_unit,context_digest:item.context_digest};
const candidate={decision_id:'decision.human-review-001',action:'include',anchor_ids:[item.anchor_id],source_bindings:[binding],rationale:'一次資料のURLとlocatorを人が確認し、独立Surfaceとして保持する根拠と境界を記録しました。',reviewer:'reviewer-01',reviewed_at:'2026-08-28T12:34:56+09:00',review_method:'manual-primary-source',mapping:[{old_anchor_id:item.anchor_id,new_item_ids:['surface.reviewed-example']}],result_items:[{id:'surface.reviewed-example',item_type:'surface'}]};

test('固定read-only exportと2 Schemaは80 packet・230 projection・113 proposalを保持する',()=>{assert.equal(bundle.ok,true,JSON.stringify(bundle.errors));const value=bundle.archive.reviewExport;assert.equal(value.mode,'read-only');assert.equal(value.summary.packets,80);assert.equal(value.summary.candidate_domain_projections,230);assert.equal(value.summary.proposed_clusters,113);assert.equal(value.summary.pending_human,80);assert.equal(value.summary.human_reviewed,0);assert.equal(bundle.progress.hasHumanProgress,false);});
test('machine proposalをHuman decisionとして扱わずPortal書込みを拒否する',()=>{const value=bundle.archive.reviewExport;assert.equal(value.capabilities.write_decisions,false);assert.equal(value.capabilities.promote_human_review,false);assert.equal(value.decision_boundary.export_accepts_writes,false);assert.equal(value.decision_boundary.decisions_observed,0);assert.ok(value.proposed_clusters.every((proposal)=>proposal.semantic_decision==='none-machine-proposal-only'&&proposal.human_reviewed===false));assert.ok(bundle.archive.packets.every(({value:reviewPacket})=>reviewPacket.semantic_decision==='none-by-export'&&reviewPacket.read_only===true&&reviewPacket.decision_boundary.human_decision_recorded===false));});
test('3 stale relock候補は選択前read-only holdを保つ',()=>{const value=bundle.archive.reviewExport;assert.equal(value.stale_holds.length,3);assert.equal(value.stale_candidate_report.human_choices,0);assert.equal(value.stale_candidate_report.locked_digests_updated,0);assert.ok(value.stale_holds.every((hold)=>hold.status==='hold-stale-document-relock-required'));});
test('将来のCore共通API境界は完全なmanual-primary-source Decisionだけを受理する',()=>{const result=validateAuthorityReviewCandidate(candidate,bundle.itemById);assert.equal(result.ok,true,JSON.stringify(result.errors));assert.equal(result.countsAsReviewed,true);});
test('自動判定をHuman reviewとして保存しない',()=>{for(const reviewer of ['automated-review','agent.queue','bot system','machine-01']){const result=validateAuthorityReviewCandidate({...candidate,reviewer},bundle.itemById);assert.equal(result.ok,false);assert.ok(result.errors.some((error)=>error.includes('自動主体')));}});
test('reason/reviewer/time/manual-primary-source/digest/mapping欠落をすべて拒否する',()=>{const cases=[{value:{...candidate,rationale:''},token:'reason'},{value:{...candidate,reviewer:''},token:'reviewer'},{value:{...candidate,reviewed_at:''},token:'time'},{value:{...candidate,review_method:'machine'},token:'manual-primary-source'},{value:{...candidate,source_bindings:[{...binding,context_digest:''}]},token:'digest'},{value:{...candidate,mapping:[]},token:'mapping'}];for(const fixture of cases){const result=validateAuthorityReviewCandidate(fixture.value,bundle.itemById);assert.equal(result.ok,false);assert.ok(result.errors.some((error)=>error.toLowerCase().includes(fixture.token)),`${fixture.token}: ${result.errors}`);}});
test('packetはURL・locator・digestのみを持ち一次資料本文を持たない',()=>{for(const{value:reviewPacket}of bundle.archive.packets){assert.match(reviewPacket.source_binding.document_url,/^https:\/\//);assert.ok(reviewPacket.source_binding.locator);for(const key of ['locked_source_digest','inventory_tool_digest','review_queue_tool_digest','context_digest'])assert.match(reviewPacket.source_binding[key],/^sha256:[a-f0-9]{64}$/);for(const forbidden of ['body','text','content','html','excerpt']){assert.equal(Object.hasOwn(reviewPacket,forbidden),false);assert.equal(Object.hasOwn(reviewPacket.source_binding,forbidden),false);}}});
