import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { missingDefinitiveV2, projectDefinitiveV2, validateDefinitiveV2Envelope } from '../scripts/lib/definitive-v2.mjs';
import { sha256 } from '../scripts/lib/crypto.mjs';

const root=process.cwd();
const lock=JSON.parse(await readFile(path.join(root,'contracts/definitive-v2-lock.json'),'utf8'));
const schemas={
  definitive:JSON.parse(await readFile(path.join(root,'contracts/schemas/definitive.schema.json'),'utf8')),
  migration:JSON.parse(await readFile(path.join(root,'contracts/schemas/definitive-migration.schema.json'),'utf8')),
  certificate:JSON.parse(await readFile(path.join(root,'contracts/schemas/definitive-certificate.schema.json'),'utf8')),
};
const digest='sha256:'+'a'.repeat(64);const commit='b'.repeat(40);

function envelope(result='pass'){
  const definitive={schema_version:2,atlas_id:'test-atlas',epoch:'2026-08-30',completion_class:'subject-definitive',authority_extraction:'authority/extraction.snapshot.json',authority_body_inventory:'authority/body-inventory.snapshot.json',authority_body_review:'authority/review-queue.snapshot.json',surface_inventory:'surface.inventory.yaml',verification_matrix:'verification.matrix.yaml',scenario_proofs:'evidence/scenarios/index.json',scenario_closure_plan:'evidence/scenarios/closure-plan.json',evidence_durability:'artifacts/pattern-scenarios/results.json',evidence_dependency_graph:'evidence/dependency-graph.json',skill_eval:'evals/test.definitive-skill-eval.json',skill_router:'evals/definitive-skill-router.json',certificate:'evidence/definitive-certificate.json',historical_certificates:[{path:'evidence/history/v1/completion-certificate.json',classification:'bounded-complete'}],reference_systems:[],comparisons:[]};
  const migration={schema_version:2,atlas_id:'test-atlas',from:'bounded-complete-v1',to:'subject-definitive-v2',generated_at:'2026-08-30T00:00:00Z',historical_certificate:{path:'evidence/history/v1/completion-certificate.json',digest,classification:'bounded-complete'},status:'ready-for-audit',required_actions:['lock-authority-artifacts','extract-authority-locators','classify-all-surfaces','issue-definitive-certificate']};
  const certificate={schema_version:2,completion_class:'subject-definitive',atlas_id:'test-atlas',atlas_release:'v2.0.0',coverage_epoch:'2026-08-30',authority_lock_digest:digest,authority_extraction_digest:digest,authority_body_inventory_digest:digest,authority_body_review_digest:digest,surface_inventory_digest:digest,verification_matrix_digest:digest,scenario_proof_digest:digest,scenario_closure_plan_digest:digest,evidence_durability_digest:digest,evidence_dependency_digest:digest,depth_parity_digest:digest,proof_graph_digest:digest,skill_eval_digest:digest,reference_system_digest:digest,non_regression_digest:digest,historical_certificates:[{path:'evidence/history/v1/completion-certificate.json',classification:'bounded-complete',digest}],issued_at:'2026-08-30T00:00:00Z',commit};
  certificate.signature={type:'payload-sha256',digest:sha256(certificate)};
  const payload={subjectId:'test-atlas',atlasId:'test-atlas',repository:'test-atlas',sourceCommit:commit,releaseDigest:digest,coreCommit:lock.coreCommit,definitive,definitiveDigest:sha256(definitive),migration,migrationDigest:sha256(migration),certificate,certificateDigest:sha256(certificate)};
  payload.coreGate={schemaVersion:1,coreCommit:lock.coreCommit,command:lock.gateCommand,result,executedAt:'2026-08-30T00:00:00Z',runtimeIdentity:{coreVersion:'v2'},releaseDigest:payload.releaseDigest,definitiveDigest:payload.definitiveDigest,certificateDigest:payload.certificateDigest,migrationDigest:payload.migrationDigest,inventoryClosure:{status:result==='pass'?'closed':'open',required:4,classified:result==='pass'?4:3,unclassified:result==='pass'?0:1,openRequired:result==='pass'?0:1,excluded:1,infeasible:1},runtimeProfiles:[{id:'linux',status:result==='pass'?'current':'stale',runtimeIdentity:{os:'linux'}}],gapIds:result==='pass'?[]:['target.open'],diagnostics:result==='pass'?[]:['required target open']};
  return {kind:'portal-definitive-v2',payload,release:{digest:sha256(payload)}};
}

test('Core正式mainの3 Schemaをbyte digestで固定する',async()=>{assert.equal(lock.coreCommit,'072d7ca77981f51754e824d70c6d4ecd55ea67e5');for(const[file,key]of [['definitive.schema.json','definitiveSchemaDigest'],['definitive-migration.schema.json','migrationSchemaDigest'],['definitive-certificate.schema.json','certificateSchemaDigest']])assert.equal(sha256(await readFile(path.join(root,'contracts/schemas',file))),lock[key]);});
test('Subject入力欠落は既知Gapとv1観測情報を残してfail-closedにする',()=>{const value=missingDefinitiveV2({id:'sample'},{atlasId:'sample',coverage:{openRequired:2,states:{excluded:3,infeasible:4}},observedProfiles:['container']});assert.equal(value.status,'subject-definitive-input-missing');assert.equal(value.completionClass,'not-definitive');assert.equal(value.coreGate.result,'not-run');assert.deepEqual(value.inventoryClosure,{status:'not-evaluated',required:null,classified:null,unclassified:null,openRequired:2,excluded:3,infeasible:4});assert.equal(value.runtimeProfiles[0].status,'v1-evidence-observed-not-v2-verified');assert.equal(value.readOnly,true);assert.equal(value.autoPromotion,false);assert.ok(value.gapIds.includes('core-gate:definitive'));});
test('公開TrustとCore Gate passが揃う場合だけsubject-definitiveへ投影する',()=>{const value=envelope();const validated=validateDefinitiveV2Envelope(value,lock,schemas,{ok:true,errors:[],trust:{usage:'public-release'}});assert.equal(validated.ok,true,validated.errors.join('; '));const projected=projectDefinitiveV2(value,validated,{trust:{usage:'public-release'}});assert.equal(projected.status,'subject-definitive');assert.equal(projected.inventoryClosure.unclassified,0);assert.equal(projected.autoPromotion,false);});
test('fixture Trust、Gapあり、digest不一致はDefinitive入力として拒否する',()=>{const fixture=envelope();const fixtureResult=validateDefinitiveV2Envelope(fixture,lock,schemas,{ok:true,errors:[],trust:{usage:'fixture-only'}});assert.equal(fixtureResult.ok,false);assert.match(fixtureResult.errors.join('\n'),/公開Trust Key/);const failed=envelope('fail');const failedResult=validateDefinitiveV2Envelope(failed,lock,schemas,{ok:true,errors:[],trust:{usage:'public-release'}});assert.equal(failedResult.ok,true,failedResult.errors.join('; '));assert.equal(projectDefinitiveV2(failed,failedResult,{trust:{usage:'public-release'}}).status,'subject-definitive-incomplete');const changed=envelope();changed.payload.releaseDigest='sha256:'+'c'.repeat(64);const changedResult=validateDefinitiveV2Envelope(changed,lock,schemas,{ok:true,errors:[],trust:{usage:'public-release'}});assert.equal(changedResult.ok,false);assert.match(changedResult.errors.join('\n'),/releaseDigest binding/);});
