import assert from 'node:assert/strict';
import { cp, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { classifySubjectCompletion, loadTrust, schemaValidators, validateCompletionCertificate, validateRelease, verifyEnvelope } from '../scripts/lib/validate.mjs';

const root = process.cwd();
const fixtureRoot = path.join(root,'fixtures');
const registry = JSON.parse(await readFile(path.join(fixtureRoot,'registry.json'),'utf8'));
const trusted = await loadTrust(fixtureRoot);
const envelope = JSON.parse(await readFile(path.join(fixtureRoot,registry.releases[0].file),'utf8'));

test('署名済みfixture Releaseを受理する', () => assert.equal(verifyEnvelope(envelope,trusted).ok,true));
test('署名後にPayloadが変わったReleaseを隔離する', () => { const tampered=structuredClone(envelope);tampered.payload.atlas.title+='改変';assert.equal(verifyEnvelope(tampered,trusted).ok,false); });
test('署名値が不正なReleaseを隔離する', () => { const tampered=structuredClone(envelope);tampered.signature.value=`A${tampered.signature.value.slice(1)}`;assert.equal(verifyEnvelope(tampered,trusted).ok,false); });
test('未知の鍵を拒否する', () => { const tampered=structuredClone(envelope);tampered.signature.keyId='unknown';assert.equal(verifyEnvelope(tampered,trusted).ok,false); });
test('Trust Storeのfixture-only分類を失わない', () => assert.equal(verifyEnvelope(envelope,trusted).trust.usage,'fixture-only'));
test('completeをCertificateなしで宣言したReleaseを拒否する', async () => { const validators=await schemaValidators(path.join(root,'contracts/schemas'));const payload=structuredClone(envelope.payload);payload.atlas.status='complete';const result=validateRelease(payload,validators,envelope.release);assert.equal(result.ok,false);assert.ok(result.errors.some((error)=>error.includes('Completion Certificate'))); });
test('CertificateのPayload digest改変を拒否する', async () => { const validators=await schemaValidators(path.join(root,'contracts/schemas'));const payload=structuredClone(envelope.payload);payload.certificate=JSON.parse(await readFile(path.join(root,'evidence/completion-certificate.json'),'utf8'));payload.certificate.atlas_id=payload.atlas.id;payload.certificate.atlas_release=payload.skillPackage.atlas_release;payload.certificate.coverage_epoch=payload.atlas.coverage.epoch;payload.certificate.authority_lock_digest=payload.coverage.authority_lock_digest;payload.certificate.core_policy_version=payload.atlas.completion.policy_version;const result=validateCompletionCertificate(payload,validators,envelope.release);assert.equal(result.ok,false);assert.ok(result.errors.some((error)=>error.includes('payload digest'))); });
test('公開Trust付きv1 Certificateもbounded historicalでDefinitiveへ昇格しない', () => { const payload=structuredClone(envelope.payload);payload.certificate={schema_version:1,core_policy_version:'1.0.0',coverage_epoch:'2026-08-28'};const result=classifySubjectCompletion(payload,{ok:true},{usage:'public-release'});assert.equal(result.classification,'bounded-historical');assert.equal(result.definitive,false);assert.equal(result.trustUsage,'public-release'); });
test('CertificateなしをDefinitiveへ自動昇格しない', () => { const result=classifySubjectCompletion(envelope.payload,{present:false,ok:true},{usage:'public-release'});assert.equal(result.classification,'not-definitive');assert.equal(result.definitive,false); });
test('97件とRelease履歴を欠落なく索引する', async () => { const index=JSON.parse(await readFile(path.join(root,'app/data/index.generated.json'),'utf8'));assert.equal(index.subjects.length,97);assert.equal(index.verification.absent,90);assert.ok(index.subjects.every((item)=>Array.isArray(item.releaseHistory)));assert.equal(index.completionPolicy.autoPromotion,false); });
test('current Releaseの詳細をDigest固定URLから解決する', async () => { const index=JSON.parse(await readFile(path.join(root,'app/data/index.generated.json'),'utf8'));for(const subject of index.subjects.filter((item)=>item.release)){const detail=JSON.parse(await readFile(path.join(root,'public',subject.release.detailUrl),'utf8'));assert.equal(detail.digest,subject.currentReleaseDigest);} });
test('IndexとImport Reportを一時Fileからatomic replaceする', async () => { const importer=await readFile(path.join(root,'scripts/import-releases.mjs'),'utf8');assert.match(importer,/rename\(outputTemporary, output\)/);assert.match(importer,/rename\(reportTemporary, reportPath\)/); });
test('隔離Releaseがある場合はlast-known-good Indexを更新しない', async () => { const temporary=await mkdtemp(path.join(os.tmpdir(),'atlas-portal-lkg-'));try{const copiedFixtures=path.join(temporary,'fixtures');await cp(fixtureRoot,copiedFixtures,{recursive:true});const copiedRegistry=JSON.parse(await readFile(path.join(copiedFixtures,'registry.json'),'utf8'));const badPath=path.join(copiedFixtures,copiedRegistry.releases[0].file);const bad=JSON.parse(await readFile(badPath,'utf8'));bad.payload.atlas.title+='改変';await writeFile(badPath,JSON.stringify(bad));const output=path.join(temporary,'index.json');const report=path.join(temporary,'report.json');await writeFile(output,'last-known-good\n');const result=spawnSync(process.execPath,[path.join(root,'scripts/import-releases.mjs'),copiedFixtures,output,report],{cwd:root,encoding:'utf8'});assert.notEqual(result.status,0);assert.equal(await readFile(output,'utf8'),'last-known-good\n');assert.equal(JSON.parse(await readFile(report,'utf8')).verdict,'fail');}finally{await rm(temporary,{recursive:true,force:true});} });
