import assert from 'node:assert/strict';
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { evaluateNonRegression } from '../scripts/lib/non-regression.mjs';

const root = process.cwd();
const readJson = async (file) => JSON.parse(await readFile(file, 'utf8'));
const writeJson = async (file, value) => writeFile(file, `${JSON.stringify(value, null, 2)}\n`);

test('凍結Baselineは97 Subject・246 Target・45 Evidenceを個別に保護する', async () => {
  const result = await evaluateNonRegression(root);
  assert.equal(result.verdict, 'pass');
  assert.deepEqual({ subjects:result.summary.baselineSubjects, targets:result.summary.baselineTargets, evidence:result.summary.baselineEvidence, failures:result.summary.failureScenarios }, { subjects:97, targets:246, evidence:45, failures:11 });
});

test('削除・格上げ・不可視化・粒度低下を拒否する', async () => {
  const temporary = await mkdtemp(path.join(os.tmpdir(), 'atlas-non-regression-'));
  try {
    for (const directory of ['contracts','contracts/reference','contracts/schemas','app/data','evidence','evidence/scenarios','evidence/reports','fixtures/depth-references','fixtures/fixed-commit-audits','fixtures/portal-root-surface-inventory','fixtures/portal-distribution-readiness','public','public/data/releases','public/data/authority-reviews','public/data/fixed-commit-audits','public/data/index']) await mkdir(path.join(temporary,directory), { recursive:true });
    for (const file of ['mastery.yaml','coverage.yaml','verification.matrix.yaml','sbom.spdx.json','contracts/non-regression-baseline.json','contracts/non-regression-mappings.json','contracts/depth-reference-lock.json','contracts/authority-review-lock.json','contracts/evidence-dependency-lock.json','contracts/definitive-v2-lock.json','contracts/portal-root-definitive-lock.json','contracts/portal-root-surface-inventory.json','contracts/portal-content-addressed-index-migration.json','contracts/portal-dependency-reproduce-order.json','contracts/schemas/portal-distribution-readiness.schema.json','contracts/schemas/portal-content-addressed-index-migration.schema.json','contracts/schemas/portal-dependency-reproduce-order.schema.json','contracts/fixed-commit-audit-lock.json','contracts/fixed-commit-audit-postgresql-lock.json','contracts/fixed-commit-audit-flutter-lock.json','contracts/fixed-commit-audit-rabbitmq-lock.json','contracts/fixed-commit-audit-kotlin-lock.json','contracts/fixed-commit-audit-zero-trust-lock.json','contracts/fixed-commit-audit-frontend-behavior-lock.json','contracts/reference/MIGRATION_DEFINITIVE_V2.md','app/data/index.generated.json','app/data/index-bootstrap.generated.json','app/lib/verified-json.mjs','app/lib/portal-ci-checkpoint-readiness.mjs','app/lib/portal-evidence-refresh-status.mjs','app/lib/portal-integration-status.mjs','app/lib/portal-import-lifecycle-visibility.mjs','app/lib/portal-root-readiness-status.mjs','app/lib/portal-root-verification-matrix-readiness.mjs','app/api/ci-checkpoint-readiness/route.js','app/api/evidence-status/route.js','app/api/integration-status/route.js','app/api/import-lifecycle/route.js','app/api/root-readiness-status/route.js','app/api/root-verification-matrix-readiness/route.js','evidence/dependency-graph.json','evidence/import-report.json','evidence/import.integrity.evidence.json','evidence/non-regression.evidence.json','evidence/non-regression-report.json','evidence/ui.build.evidence.json','evidence/dependency.own-closure.evidence.json','evidence/publication.sbom.evidence.json','evidence/security.headers.evidence.json','evidence/performance.budget.evidence.json','evidence/router.eval.evidence.json','evidence/scenarios/index.json','evidence/reports/performance.json','evidence/reports/router-eval.json','evidence/portal-root-definitive-report.json','evidence/portal-distribution-readiness.json','fixtures/failure-scenarios.json','fixtures/registry.json','fixtures/registry/invalid-registry-cases.json','fixtures/portal-root-surface-inventory/negative-cases.json','fixtures/portal-distribution-readiness/negative-cases.json','fixtures/evidence-dependency/content-addressed-index-migration-negative-cases.json','fixtures/evidence-dependency/refresh-order-negative-cases.json','public/_headers','package.json','app/page.tsx']) {
      await mkdir(path.dirname(path.join(temporary,file)), { recursive:true });
      await cp(path.join(root,file), path.join(temporary,file));
    }
    for(const file of ['contracts/schemas/portal-distribution-input-bindings.schema.json','evidence/portal-distribution-input-bindings.json','fixtures/portal-distribution-input-bindings/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-distribution-gap-index.schema.json','evidence/portal-distribution-gap-index.json','fixtures/portal-distribution-gap-index/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-root-artifact-gap-index.schema.json','evidence/portal-root-artifact-gap-index.json','fixtures/portal-root-artifact-gap-index/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-distribution-verification-matrix.schema.json','evidence/portal-distribution-verification-matrix.json','fixtures/portal-distribution-verification-matrix/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-import-lifecycle-visibility.schema.json','evidence/portal-import-lifecycle-visibility.json','fixtures/portal-import-lifecycle-visibility/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-root-readiness-status.schema.json','fixtures/portal-root-readiness-status/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-root-depth-parity-readiness.schema.json','evidence/portal-root-depth-parity-readiness.json','fixtures/portal-root-depth-parity-readiness/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-root-migration-readiness.schema.json','evidence/portal-root-migration-readiness.json','fixtures/portal-root-migration-readiness/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-root-definitive-certificate-readiness.schema.json','evidence/portal-root-definitive-certificate-readiness.json','fixtures/portal-root-definitive-certificate-readiness/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-root-definitive-declaration-readiness.schema.json','evidence/portal-root-definitive-declaration-readiness.json','fixtures/portal-root-definitive-declaration-readiness/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-root-surface-inventory-readiness.schema.json','evidence/portal-root-surface-inventory-readiness.json','fixtures/portal-root-surface-inventory-readiness/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-root-verification-matrix-readiness.schema.json','evidence/portal-root-verification-matrix-readiness.json','fixtures/portal-root-verification-matrix-readiness/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-ci-checkpoint-readiness.schema.json','evidence/portal-ci-checkpoint-readiness.json','fixtures/portal-ci-checkpoint-readiness/negative-cases.json']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    for(const file of ['contracts/schemas/portal-evidence-refresh-policy.schema.json','contracts/portal-evidence-refresh-policy.json','fixtures/portal-evidence-refresh-policy/negative-cases.json','contracts/schemas/portal-integration-status.schema.json','fixtures/portal-integration-status/negative-cases.json','scripts/atlas-portal.mjs']){await mkdir(path.dirname(path.join(temporary,file)),{recursive:true});await cp(path.join(root,file),path.join(temporary,file));}
    await mkdir(path.join(temporary,'contracts/reference'),{recursive:true});await cp(path.join(root,'contracts/reference/MIGRATION_DEFINITIVE_V2.md'),path.join(temporary,'contracts/reference/MIGRATION_DEFINITIVE_V2.md'));
    await cp(path.join(root,'evidence/completion-certificate.json'),path.join(temporary,'evidence/completion-certificate.json'));
    await cp(path.join(root,'public/data/releases'), path.join(temporary,'public/data/releases'), { recursive:true });
    await cp(path.join(root,'public/data/authority-reviews'), path.join(temporary,'public/data/authority-reviews'), { recursive:true });
    await cp(path.join(root,'public/data/fixed-commit-audits'), path.join(temporary,'public/data/fixed-commit-audits'), { recursive:true });
    await cp(path.join(root,'public/data/index'), path.join(temporary,'public/data/index'), { recursive:true });
    await cp(path.join(root,'fixtures/depth-references'), path.join(temporary,'fixtures/depth-references'), { recursive:true });
    await cp(path.join(root,'fixtures/fixed-commit-audits'), path.join(temporary,'fixtures/fixed-commit-audits'), { recursive:true });
    const indexPath = path.join(temporary,'app/data/index.generated.json');
    const failuresPath = path.join(temporary,'fixtures/failure-scenarios.json');
    const mappingsPath = path.join(temporary,'contracts/non-regression-mappings.json');
    const migrationPath = path.join(temporary,'contracts/portal-content-addressed-index-migration.json');
    const pagePath = path.join(temporary,'app/page.tsx');
    const verifierPath=path.join(temporary,'app/lib/verified-json.mjs');
    const bootstrapPath=path.join(temporary,'app/data/index-bootstrap.generated.json');
    const rootDefinitiveReportPath=path.join(temporary,'evidence/portal-root-definitive-report.json');
    const originalIndex = await readJson(indexPath);
    const originalBootstrap=await readJson(bootstrapPath);
    const originalRootDefinitiveReport=await readJson(rootDefinitiveReportPath);
    const publicIndexPath=path.join(temporary,`public${originalBootstrap.publicUrl}`);
    const originalPublicIndex=await readFile(publicIndexPath);
    const originalFailuresBytes=await readFile(failuresPath);const originalFailures = JSON.parse(originalFailuresBytes);
    const originalMappings = await readJson(mappingsPath);
    const originalMigration = await readJson(migrationPath);
    const originalPage = await readFile(pagePath,'utf8');
    const originalVerifier=await readFile(verifierPath,'utf8');
    const expectViolation = async (code) => { const result=await evaluateNonRegression(temporary,{scanLanguage:false});assert.equal(result.verdict,'fail');assert.ok(result.violations.some((item)=>item.code===code),`${code}: ${JSON.stringify(result.violations)}`); };

    const withoutSubject=structuredClone(originalIndex);withoutSubject.subjects.shift();await writeJson(indexPath,withoutSubject);await expectViolation('subject-deleted');await writeJson(indexPath,originalIndex);
    const replacedSubject=structuredClone(originalIndex);replacedSubject.subjects[0].repository='replacement-without-old-id-mapping';await writeJson(indexPath,replacedSubject);await expectViolation('subject-identity-replaced-without-mapping');await writeJson(indexPath,originalIndex);
    const promoted=structuredClone(originalIndex);const planned=promoted.subjects.find((subject)=>subject.status==='planned');planned.status='complete';await writeJson(indexPath,promoted);await expectViolation('catalog-status-promoted');await writeJson(indexPath,originalIndex);
    const bounded=structuredClone(originalIndex);bounded.subjects.find((subject)=>subject.release).releaseHistory[0].completion={classification:'bounded-historical',definitive:true,certificateSchemaVersion:1};await writeJson(indexPath,bounded);await expectViolation('bounded-promoted-to-definitive');await writeJson(indexPath,originalIndex);
    const releasePromoted=structuredClone(originalIndex);releasePromoted.subjects.find((subject)=>subject.release).releaseHistory[0].status='complete';await writeJson(indexPath,releasePromoted);await expectViolation('release-history-status-rewritten');await writeJson(indexPath,originalIndex);
    const releaseArtifact=originalIndex.subjects.find((subject)=>subject.release).release;const releaseArtifactPath=path.join(temporary,`public${releaseArtifact.detailUrl}`);const originalReleaseArtifact=await readFile(releaseArtifactPath);await writeFile(releaseArtifactPath,Buffer.concat([originalReleaseArtifact,Buffer.from(' ')]));await expectViolation('release-detail-artifact-digest-mismatch');await writeFile(releaseArtifactPath,originalReleaseArtifact);

    const targetSubject=originalIndex.subjects.find((subject)=>subject.release?.coverage.required>0);const targetDetailPath=path.join(temporary,'public',targetSubject.release.detailUrl);const targetDetail=await readJson(targetDetailPath);const originalTargetDetail=structuredClone(targetDetail);targetDetail.targets.shift();await writeJson(targetDetailPath,targetDetail);await expectViolation('target-history-deleted');await writeJson(targetDetailPath,originalTargetDetail);
    const targetRewritten=structuredClone(originalTargetDetail);targetRewritten.targets[0].state=targetRewritten.targets[0].state==='covered'?'planned':'covered';await writeJson(targetDetailPath,targetRewritten);await expectViolation('target-history-status-rewritten');await writeJson(targetDetailPath,originalTargetDetail);
    const evidenceSubject=originalIndex.subjects.find((subject)=>subject.release?.evidenceCount>0);const evidenceDetailPath=path.join(temporary,'public',evidenceSubject.release.detailUrl);const evidenceDetail=await readJson(evidenceDetailPath);const originalEvidenceDetail=structuredClone(evidenceDetail);evidenceDetail.evidence.shift();await writeJson(evidenceDetailPath,evidenceDetail);await expectViolation('evidence-history-deleted');await writeJson(evidenceDetailPath,originalEvidenceDetail);
    const evidenceRewritten=structuredClone(originalEvidenceDetail);evidenceRewritten.evidence[0].verdict=evidenceRewritten.evidence[0].verdict==='pass'?'fail':'pass';await writeJson(evidenceDetailPath,evidenceRewritten);await expectViolation('evidence-history-rewritten');await writeJson(evidenceDetailPath,originalEvidenceDetail);

    const failures=structuredClone(originalFailures);failures.scenarios=failures.scenarios.filter((scenario)=>scenario.id!=='coverage-infeasible');await writeJson(failuresPath,failures);await expectViolation('failure-scenario-deleted');await writeFile(failuresPath,originalFailuresBytes);
    await writeFile(pagePath,originalPage.replace("const [status, setStatus] = useState('')","const [status, setStatus] = useState('release:complete')"));await expectViolation('filter-default-excludes');await writeFile(pagePath,originalPage);
    await writeFile(verifierPath,originalVerifier.toString().replace('detail artifact digest mismatch','detail accepted without digest'));await expectViolation('authority-review-browser-integrity-reduced');await writeFile(verifierPath,originalVerifier);
    const mappings=structuredClone(originalMappings);mappings.subjectMappings.push({from:originalIndex.subjects[0].id,to:originalIndex.subjects[0].id});await writeJson(mappingsPath,mappings);await expectViolation('invalid-subject-mapping');await writeJson(mappingsPath,originalMappings);
    const depthSubject=originalIndex.subjects.find((subject)=>subject.id==='frontend-behavior');const depthDetailPath=path.join(temporary,'public',depthSubject.release.detailUrl);const depthDetail=await readJson(depthDetailPath);const originalDepthDetail=structuredClone(depthDetail);depthDetail.depthReference.axes.shift();await writeJson(depthDetailPath,depthDetail);await expectViolation('depth-reference-axis-information-reduced');await writeJson(depthDetailPath,originalDepthDetail);
    const depthPromoted=structuredClone(originalIndex);depthPromoted.subjects.find((subject)=>subject.id==='frontend-behavior').depthReference.completion.definitive=true;await writeJson(indexPath,depthPromoted);await expectViolation('depth-reference-status-promoted');await writeJson(indexPath,originalIndex);
    const reviewProgress=structuredClone(originalIndex);const reviewSubject=reviewProgress.subjects.find((subject)=>subject.id==='frontend-behavior');reviewSubject.authorityReview.summary.human_reviewed=1;reviewSubject.authorityReview.summary.has_human_progress=true;await writeJson(indexPath,reviewProgress);await expectViolation('authority-review-summary-rewritten');await writeJson(indexPath,originalIndex);
    const dependencyPromoted=structuredClone(originalIndex);dependencyPromoted.subjects[0].evidenceDependency={...dependencyPromoted.subjects[0].evidenceDependency,availability:'missing',status:'current',autoPromotion:true,coreGate:{...dependencyPromoted.subjects[0].evidenceDependency.coreGate,result:'pass'}};await writeJson(indexPath,dependencyPromoted);await expectViolation('evidence-dependency-write-boundary-weakened');await writeJson(indexPath,originalIndex);
    const definitivePromoted=structuredClone(originalIndex);definitivePromoted.subjects[0].definitiveV2={...definitivePromoted.subjects[0].definitiveV2,availability:'missing',status:'subject-definitive',autoPromotion:true,coreGate:{...definitivePromoted.subjects[0].definitiveV2.coreGate,result:'pass'}};await writeJson(indexPath,definitivePromoted);await expectViolation('definitive-v2-write-boundary-weakened');await writeJson(indexPath,originalIndex);
    const definitiveAggregated=structuredClone(originalIndex);definitiveAggregated.definitiveV2Summary.gapCounts=[];definitiveAggregated.definitiveV2Summary.gapInstances=0;await writeJson(indexPath,definitiveAggregated);await expectViolation('definitive-v2-summary-information-reduced');await writeJson(indexPath,originalIndex);
    const definitiveGapHidden=structuredClone(originalIndex);definitiveGapHidden.subjects[0].definitiveV2.gapIds.pop();await writeJson(indexPath,definitiveGapHidden);await expectViolation('definitive-v2-gap-information-reduced');await writeJson(indexPath,originalIndex);
    const fixedAuditPromoted=structuredClone(originalIndex);const audited=fixedAuditPromoted.subjects.find((subject)=>subject.fixedCommitAudit?.availability==='available');audited.fixedCommitAudit.autoPromotion=true;await writeJson(indexPath,fixedAuditPromoted);await expectViolation('fixed-commit-audit-promoted');await writeJson(indexPath,originalIndex);
    const fixedAuditGapHidden=structuredClone(originalIndex);fixedAuditGapHidden.subjects.find((subject)=>subject.fixedCommitAudit?.availability==='available').fixedCommitAudit.gapCount-=1;await writeJson(indexPath,fixedAuditGapHidden);await expectViolation('fixed-commit-audit-gaps-reduced');await writeJson(indexPath,originalIndex);
    const fixedAuditArtifact=originalIndex.subjects.find((subject)=>subject.fixedCommitAudit?.availability==='available').fixedCommitAudit;const fixedAuditArtifactPath=path.join(temporary,`public${fixedAuditArtifact.detailUrl}`);const originalFixedAuditArtifact=await readFile(fixedAuditArtifactPath);await writeFile(fixedAuditArtifactPath,Buffer.concat([originalFixedAuditArtifact,Buffer.from(' ')]));await expectViolation('fixed-commit-audit-artifact-digest-mismatch');await writeFile(fixedAuditArtifactPath,originalFixedAuditArtifact);
    const missingAuditPromoted=structuredClone(originalIndex);const missingAudit=missingAuditPromoted.subjects.find((subject)=>subject.fixedCommitAudit?.availability==='missing');missingAudit.fixedCommitAudit.status='fixed-commit-incomplete';missingAudit.fixedCommitAudit.coreGate.result='pass';await writeJson(indexPath,missingAuditPromoted);await expectViolation('fixed-commit-audit-missing-promoted');await writeJson(indexPath,originalIndex);
    const bootstrapPromoted=structuredClone(originalBootstrap);bootstrapPromoted.completionSummary.subjectDefinitive=97;await writeJson(bootstrapPath,bootstrapPromoted);await expectViolation('index-bootstrap-fail-closed');await writeJson(bootstrapPath,originalBootstrap);
    const rootDistributionPromoted=structuredClone(originalRootDefinitiveReport);rootDistributionPromoted.boundary.distributionStatus='established';rootDistributionPromoted.boundary.distributionGapEffect='closed';rootDistributionPromoted.boundary.completionEffect='complete';await writeJson(rootDefinitiveReportPath,rootDistributionPromoted);await expectViolation('portal-root-distribution-boundary');await writeJson(rootDefinitiveReportPath,originalRootDefinitiveReport);
    const rootBindingsReduced=structuredClone(originalRootDefinitiveReport);rootBindingsReduced.distributionInputBindings.summary.unboundDefinitiveSubjects=0;await writeJson(rootDefinitiveReportPath,rootBindingsReduced);await expectViolation('portal-root-distribution-input-binding');await writeJson(rootDefinitiveReportPath,originalRootDefinitiveReport);
    const rootGapsClosed=structuredClone(originalRootDefinitiveReport);rootGapsClosed.distributionGapIndex.summary.openInstances=0;rootGapsClosed.distributionGapIndex.summary.closedInstances=589;await writeJson(rootDefinitiveReportPath,rootGapsClosed);await expectViolation('portal-root-distribution-gap-binding');await writeJson(rootDefinitiveReportPath,originalRootDefinitiveReport);
    const rootArtifactsHidden=structuredClone(originalRootDefinitiveReport);rootArtifactsHidden.rootArtifactGapIndex.summary.missingArtifacts=0;rootArtifactsHidden.rootArtifactGapIndex.summary.presentArtifacts=6;await writeJson(rootDefinitiveReportPath,rootArtifactsHidden);await expectViolation('portal-root-artifact-gap-binding');await writeJson(rootDefinitiveReportPath,originalRootDefinitiveReport);
    const rootMatrixPromoted=structuredClone(originalRootDefinitiveReport);rootMatrixPromoted.distributionVerificationMatrix.boundary.coreSubjectArtifact.status='present';rootMatrixPromoted.distributionVerificationMatrix.boundary.coreSubjectArtifact.effect='closed';await writeJson(rootDefinitiveReportPath,rootMatrixPromoted);await expectViolation('portal-root-distribution-matrix-binding');await writeJson(rootDefinitiveReportPath,originalRootDefinitiveReport);
    await writeFile(pagePath,originalPage.replace('distributionBindings.summary.unboundDefinitiveSubjects','distributionBindings.summary.hiddenDefinitiveSubjects'));await expectViolation('portal-distribution-ui-reduced');await writeFile(pagePath,originalPage);
    await writeFile(publicIndexPath,Buffer.concat([originalPublicIndex,Buffer.from(' ')]));await expectViolation('content-addressed-index-bytes');await writeFile(publicIndexPath,originalPublicIndex);
    const reducedMigration=structuredClone(originalMigration);reducedMigration.preservedPaths=reducedMigration.preservedPaths.filter((item)=>item!==reducedMigration.replacements[0].from.path);await writeJson(migrationPath,reducedMigration);await expectViolation('content-addressed-index-history-contract');await writeJson(migrationPath,originalMigration);
    const restoredResult=await evaluateNonRegression(temporary,{scanLanguage:false});assert.equal(restoredResult.verdict,'pass',JSON.stringify(restoredResult.violations));
  } finally {
    await rm(temporary,{recursive:true,force:true});
  }
});
