import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { assertPortalIntegrationStatusSnapshot, isPortalIntegrationStatusSnapshot } from '../app/lib/portal-integration-status.mjs';
import { applyPortalIntegrationStatusNegative, evaluatePortalIntegrationStatus, validatePortalIntegrationStatus } from '../scripts/lib/portal-integration-status.mjs';

const root=process.cwd();const negative=JSON.parse(await readFile(path.join(root,'fixtures/portal-integration-status/negative-cases.json'),'utf8'));

test('root Matrix・97 Subject配布Gap・Evidence freshnessを一つのread-only観測へ結ぶ',async()=>{const result=await evaluatePortalIntegrationStatus(root);assert.equal(result.ok,true,result.errors.join(', '));const report=result.report;assert.equal(report.status,'blocked');assert.deepEqual({required:report.root.artifactsRequired,missing:report.root.artifactsMissing,present:report.root.artifactsPresent},{required:6,missing:5,present:1});assert.deepEqual({prerequisites:report.root.matrixPrerequisites,satisfied:report.root.matrixSatisfied,blocked:report.root.matrixBlocked,cells:report.root.matrixCells,verified:report.root.matrixVerified,gap:report.root.matrixGap,notEvaluated:report.root.matrixNotEvaluated,coreArtifactStatus:report.root.coreMatrixArtifactStatus},{prerequisites:8,satisfied:3,blocked:5,cells:970,verified:201,gap:478,notEvaluated:291,coreArtifactStatus:'present'});assert.deepEqual({subjects:report.distribution.subjects,ready:report.distribution.ready,definitive:report.distribution.subjectDefinitive,open:report.distribution.openGapInstances},{subjects:97,ready:0,definitive:0,open:589});assert.ok(['blocked','ready'].includes(report.evidenceRefresh.status));if(report.evidenceRefresh.status==='ready')assert.deepEqual(report.evidenceRefresh,{status:'ready',staleWrappers:0,inputsChangedSinceRun:0,missingOutputs:0,currentRerun:true});else assert.equal(report.evidenceRefresh.currentRerun,false);assert.equal(report.boundary.portalIsSubject,false);assert.equal(report.boundary.completionEffect,'none');});

test('root/Matrix/Subject/Gap/freshnessの隠蔽と完成昇格を拒否する',async()=>{const result=await evaluatePortalIntegrationStatus(root);assert.equal(negative.cases.length,9);for(const item of negative.cases){const checked=validatePortalIntegrationStatus(applyPortalIntegrationStatusNegative(result.report,item),result.schema,result.report);assert.equal(checked.ok,false,item.caseId);assert.ok(checked.errors.includes(item.expectedDiagnostic),`${item.caseId}: ${checked.errors.join(', ')}`);}});

test('browser guardはexact denominatorとread-only境界が崩れた応答を拒否する',async()=>{const result=await evaluatePortalIntegrationStatus(root);assert.equal(isPortalIntegrationStatusSnapshot(result.report),true);assert.equal(assertPortalIntegrationStatusSnapshot(result.report),result.report);for(const item of negative.cases){assert.equal(isPortalIntegrationStatusSnapshot(applyPortalIntegrationStatusNegative(result.report,item)),false,item.caseId);}assert.throws(()=>assertPortalIntegrationStatusSnapshot({status:'ready'}),/invalid/);});

test('CLIは統合状態を表示して正本を変更しない',async()=>{const protectedPaths=['evidence/portal-root-artifact-gap-index.json','evidence/portal-root-verification-matrix-readiness.json','evidence/portal-distribution-readiness.json','evidence/portal-distribution-gap-index.json','evidence/dependency-graph.json'];const before=Object.fromEntries(await Promise.all(protectedPaths.map(async(relative)=>[relative,(await stat(path.join(root,relative))).mtimeMs])));const output=spawnSync(process.execPath,['scripts/atlas-portal.mjs','integration-status'],{cwd:root,encoding:'utf8'});assert.equal(output.status,0,output.stderr);const report=JSON.parse(output.stdout);assert.equal(report.ok,true);assert.equal(report.status,'blocked');assert.equal(report.root.artifactsMissing,5);assert.equal(report.root.coreMatrixArtifactStatus,'present');assert.equal(report.distribution.openGapInstances,589);assert.equal(report.boundary.completionEffect,'none');const unknown=spawnSync(process.execPath,['scripts/atlas-portal.mjs','integration-status','--promote'],{cwd:root,encoding:'utf8'});assert.equal(unknown.status,2);const after=Object.fromEntries(await Promise.all(protectedPaths.map(async(relative)=>[relative,(await stat(path.join(root,relative))).mtimeMs])));assert.deepEqual(after,before);});
