import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { applyPortalRootSurfaceNegative, validatePortalRootSurfaceInventory } from '../scripts/lib/portal-root-surface-inventory.mjs';

const root=process.cwd();
const lock=JSON.parse(await readFile(path.join(root,'contracts/portal-root-definitive-lock.json'),'utf8'));
const report=JSON.parse(await readFile(path.join(root,'evidence/portal-root-definitive-report.json'),'utf8'));
const surfaceInventory=JSON.parse(await readFile(path.join(root,lock.portalInfrastructureSurfaceInventory.path),'utf8'));

test('Portal root Definitive実監査失敗をbounded Certificateや配布Closureへ読み替えない',()=>{
  assert.equal(report.core.commit,lock.coreCommit);assert.equal(report.result,'fail');assert.equal(report.exitCode,1);assert.equal(report.status,'root-definitive-incomplete');assert.equal(report.completionClass,'not-definitive');assert.deepEqual(report.knownMissingArtifacts,lock.knownMissingArtifacts);assert.equal(report.failureOrdering,'core-order-independent');assert.equal(report.diagnosticClass,'known-required-root-artifact-unreadable');assert.equal(report.portalInfrastructureArtifacts.length,1);assert.deepEqual(report.portalInfrastructureArtifacts[0].denominator,{masterySurfaces:14,coverageTargets:14,sourcePolicy:'portal-v1-authored-contracts'});assert.equal(report.portalInfrastructureArtifacts[0].inventedEdges,0);assert.equal(report.distributionReadiness.path,'evidence/portal-distribution-readiness.json');assert.equal(report.distributionReadiness.status,'not-established');assert.equal(report.distributionReadiness.summary.subjects,97);assert.equal(report.distributionReadiness.summary.distributionReady,0);assert.equal(report.distributionReadiness.summary.blockerInstances,589);assert.equal(report.distributionReadiness.boundary.completionEffect,'none');assert.equal(report.distributionReadiness.boundary.autoPromotion,false);assert.equal(report.distributionInputBindings.path,'evidence/portal-distribution-input-bindings.json');assert.equal(report.distributionInputBindings.status,'incomplete');assert.equal(report.distributionInputBindings.summary.releaseBindings,7);assert.equal(report.distributionInputBindings.summary.fixedCommitAuditBindings,7);assert.equal(report.distributionInputBindings.summary.definitiveV2Bindings,0);assert.equal(report.distributionInputBindings.summary.unboundReleaseSubjects,90);assert.equal(report.distributionInputBindings.summary.unboundDefinitiveSubjects,97);assert.equal(report.distributionInputBindings.boundary.completionEffect,'none');assert.deepEqual(report.boundary,{portalBoundedCertificate:'preserved-v1-local-evidence',subjectDefinitiveEffect:'none',distributionStatus:'not-established',distributionGapEffect:'none',completionEffect:'none',autoPromotion:false});
});

test('Portal root reportは589 Distribution Gapをopenのまま固定する',()=>{
  assert.equal(report.distributionGapIndex.path,'evidence/portal-distribution-gap-index.json');assert.equal(report.distributionGapIndex.status,'open');assert.equal(report.distributionGapIndex.summary.openInstances,589);assert.equal(report.distributionGapIndex.summary.closedInstances,0);assert.equal(report.distributionGapIndex.summary.blockerTypes,8);assert.equal(report.distributionGapIndex.boundary.distributionStatus,'not-established');assert.equal(report.distributionGapIndex.boundary.completionEffect,'none');
});

test('Portal root reportは5 missing / 1 present artifactをCore契約へ結びPortalをSubject化しない',()=>{
  assert.equal(report.rootArtifactGapIndex.path,'evidence/portal-root-artifact-gap-index.json');assert.equal(report.rootArtifactGapIndex.status,'open');assert.deepEqual(report.rootArtifactGapIndex.summary,{requiredArtifacts:6,missingArtifacts:5,presentArtifacts:1,openGaps:5,closedGaps:1});assert.equal(report.rootArtifactGapIndex.boundary.portalIsSubject,false);assert.equal(report.rootArtifactGapIndex.boundary.autoCreate,false);assert.equal(report.rootArtifactGapIndex.boundary.rootDefinitiveStatus,'root-definitive-incomplete');assert.equal(report.rootArtifactGapIndex.boundary.completionEffect,'none');
});

test('Portal root reportは97×10配布MatrixとCore Subject matrix present/non-completingを分離する',()=>{
  assert.equal(report.distributionVerificationMatrix.path,'evidence/portal-distribution-verification-matrix.json');assert.equal(report.distributionVerificationMatrix.status,'incomplete');assert.deepEqual(report.distributionVerificationMatrix.summary,{subjects:97,classes:10,cells:970,verified:201,gap:478,notEvaluated:291,completionEffect:'none'});assert.deepEqual(report.distributionVerificationMatrix.boundary.coreSubjectArtifact,{path:'verification.matrix.yaml',status:'present',effect:'none'});assert.equal(report.distributionVerificationMatrix.boundary.runtimeSubstitution,false);assert.equal(report.distributionVerificationMatrix.boundary.distributionStatus,'not-established');
});

test('Portal root reportは実Import lifecycleとfixture検証を分離する',()=>{
  assert.equal(report.importLifecycleVisibility.path,'evidence/portal-import-lifecycle-visibility.json');assert.equal(report.importLifecycleVisibility.status,'incomplete');assert.deepEqual(report.importLifecycleVisibility.actual,{subjects:97,verified:7,quarantined:0,absent:90,incompleteCurrentReleases:7,publicTrustedCurrentReleases:0,expiredHistoricalReleases:0,supersededHistoricalReleases:0,archivedHistoricalReleases:0,staleHumanReviewHolds:3,definitiveV2Imports:0});assert.equal(report.importLifecycleVisibility.fixtureCoverage.fixtureOnly,true);assert.equal(report.importLifecycleVisibility.fixtureCoverage.failureScenarios,11);assert.equal(report.importLifecycleVisibility.fixtureCoverage.expiredScenarios,1);assert.equal(report.importLifecycleVisibility.boundary.completionEffect,'none');
});

test('Portal root reportはDepth parity readinessをCore artifactへ代用しない',()=>{
  assert.equal(report.rootDepthParityReadiness.path,'evidence/portal-root-depth-parity-readiness.json');assert.equal(report.rootDepthParityReadiness.status,'blocked');assert.deepEqual(report.rootDepthParityReadiness.summary,{prerequisites:6,satisfied:1,blocked:5,coreDepthParityArtifactsPresent:0,completionEffect:'none'});assert.equal(report.rootDepthParityReadiness.coreContract.artifactPath,'depth.parity.yaml');assert.equal(report.rootDepthParityReadiness.coreContract.observedStatus,'missing');assert.equal(report.rootDepthParityReadiness.observed.portalIsSubject,false);assert.equal(report.rootDepthParityReadiness.observed.dependencyGraph.boundRequiredOutputs+report.rootDepthParityReadiness.observed.dependencyGraph.missingRequiredOutputs.length,6);assert.equal(report.rootDepthParityReadiness.boundary.portalSurfaceInventoryIsCoreSubjectArtifact,false);assert.equal(report.rootDepthParityReadiness.boundary.distributionMatrixIsCoreSubjectMatrix,false);assert.equal(report.rootDepthParityReadiness.boundary.recordedGraphStatusIsCurrentProof,false);assert.equal(report.rootDepthParityReadiness.boundary.completionEffect,'none');
});

test('Portal root reportはbounded v1 sourceをMigration artifactへ代用しない',()=>{
  assert.equal(report.rootMigrationReadiness.path,'evidence/portal-root-migration-readiness.json');assert.equal(report.rootMigrationReadiness.status,'blocked');assert.deepEqual(report.rootMigrationReadiness.summary,{prerequisites:9,satisfied:2,blocked:7,migrationArtifactsPresent:0,completionEffect:'none'});assert.equal(report.rootMigrationReadiness.coreContract.artifactPath,'migrations/definitive-v2.yaml');assert.equal(report.rootMigrationReadiness.coreContract.observedStatus,'missing');assert.equal(report.rootMigrationReadiness.observed.boundedCertificate.payloadDigestValid,true);assert.equal(report.rootMigrationReadiness.observed.boundedCertificate.classification,'bounded-source-only');assert.equal(report.rootMigrationReadiness.observed.boundedCertificate.historyCopyExists,false);assert.equal(report.rootMigrationReadiness.observed.boundedCertificate.definitiveEffect,'none');assert.equal(report.rootMigrationReadiness.boundary.boundedCertificateIsDefinitive,false);assert.equal(report.rootMigrationReadiness.boundary.migrationDocumentIsMigrationArtifact,false);assert.equal(report.rootMigrationReadiness.boundary.completionEffect,'none');
});

test('Portal root reportはbounded v1をDefinitive Certificateへ代用・自動発行しない',()=>{
  assert.equal(report.rootDefinitiveCertificateReadiness.path,'evidence/portal-root-definitive-certificate-readiness.json');assert.equal(report.rootDefinitiveCertificateReadiness.status,'blocked');assert.deepEqual(report.rootDefinitiveCertificateReadiness.summary,{prerequisites:10,satisfied:1,blocked:9,definitiveCertificatesPresent:0,completionEffect:'none'});assert.equal(report.rootDefinitiveCertificateReadiness.coreContract.artifactPath,'evidence/definitive-certificate.json');assert.equal(report.rootDefinitiveCertificateReadiness.coreContract.observedStatus,'missing');assert.equal(report.rootDefinitiveCertificateReadiness.observed.boundedCertificate.payloadDigestValid,true);assert.equal(report.rootDefinitiveCertificateReadiness.observed.boundedCertificate.definitiveEffect,'none');assert.equal(report.rootDefinitiveCertificateReadiness.observed.distribution.publicTrustedRelease,0);assert.equal(report.rootDefinitiveCertificateReadiness.observed.distribution.definitiveCoreGatePassed,0);assert.equal(report.rootDefinitiveCertificateReadiness.boundary.boundedCertificateIsDefinitive,false);assert.equal(report.rootDefinitiveCertificateReadiness.boundary.autoIssue,false);assert.equal(report.rootDefinitiveCertificateReadiness.boundary.autoPromotion,false);assert.equal(report.rootDefinitiveCertificateReadiness.boundary.completionEffect,'none');
});

test('Portal root reportはPortal adapterをdefinitive.yamlへ代用・自動生成しない',()=>{
  assert.equal(report.rootDefinitiveDeclarationReadiness.path,'evidence/portal-root-definitive-declaration-readiness.json');assert.equal(report.rootDefinitiveDeclarationReadiness.status,'blocked');assert.deepEqual(report.rootDefinitiveDeclarationReadiness.summary,{prerequisites:9,satisfied:1,blocked:8,definitiveDeclarationsPresent:0,completionEffect:'none'});assert.equal(report.rootDefinitiveDeclarationReadiness.coreContract.artifactPath,'definitive.yaml');assert.equal(report.rootDefinitiveDeclarationReadiness.coreContract.observedStatus,'missing');assert.equal(report.rootDefinitiveDeclarationReadiness.observed.portalIsSubject,false);assert.equal(report.rootDefinitiveDeclarationReadiness.observed.portalSurfaceInventory.coreSubjectArtifactStatus,'missing');assert.equal(report.rootDefinitiveDeclarationReadiness.observed.distributionMatrix.coreSubjectArtifactStatus,'present');assert.equal(report.rootDefinitiveDeclarationReadiness.observed.certificate.present,0);assert.equal(report.rootDefinitiveDeclarationReadiness.boundary.portalAdapterIsCoreArtifact,false);assert.equal(report.rootDefinitiveDeclarationReadiness.boundary.autoCreate,false);assert.equal(report.rootDefinitiveDeclarationReadiness.boundary.autoPromotion,false);assert.equal(report.rootDefinitiveDeclarationReadiness.boundary.completionEffect,'none');
});

test('Portal root reportはPortal v1分母をAuthority-derived Surface Inventoryへ代用しない',()=>{
  assert.equal(report.rootSurfaceInventoryReadiness.path,'evidence/portal-root-surface-inventory-readiness.json');assert.equal(report.rootSurfaceInventoryReadiness.status,'blocked');assert.deepEqual(report.rootSurfaceInventoryReadiness.summary,{prerequisites:8,satisfied:2,blocked:6,coreSurfaceInventoryArtifactsPresent:0,completionEffect:'none'});assert.equal(report.rootSurfaceInventoryReadiness.coreContract.artifactPath,'surface.inventory.yaml');assert.equal(report.rootSurfaceInventoryReadiness.coreContract.observedStatus,'missing');assert.equal(report.rootSurfaceInventoryReadiness.observed.portalV1Denominator.masterySurfaces,14);assert.equal(report.rootSurfaceInventoryReadiness.observed.portalV1Denominator.coverageTargets,14);assert.equal(report.rootSurfaceInventoryReadiness.observed.portalV1Denominator.mappingStatus,'not-declared-in-v1-contract');assert.equal(report.rootSurfaceInventoryReadiness.observed.portalV1Denominator.inventedEdges,0);assert.equal(report.rootSurfaceInventoryReadiness.boundary.authorityDerivedDenominatorAvailable,false);assert.equal(report.rootSurfaceInventoryReadiness.boundary.portalV1DenominatorIsCoreSubjectArtifact,false);assert.equal(report.rootSurfaceInventoryReadiness.boundary.autoCreate,false);assert.equal(report.rootSurfaceInventoryReadiness.boundary.completionEffect,'none');
});

test('Portal root reportは配布MatrixをCore Subject Verification Matrixへ代用しない',()=>{
  assert.equal(report.rootVerificationMatrixReadiness.path,'evidence/portal-root-verification-matrix-readiness.json');assert.equal(report.rootVerificationMatrixReadiness.status,'blocked');assert.deepEqual(report.rootVerificationMatrixReadiness.summary,{prerequisites:8,satisfied:3,blocked:5,coreVerificationMatrixArtifactsPresent:1,completionEffect:'none'});assert.equal(report.rootVerificationMatrixReadiness.coreContract.artifactPath,'verification.matrix.yaml');assert.equal(report.rootVerificationMatrixReadiness.coreContract.observedStatus,'present');assert.equal(report.rootVerificationMatrixReadiness.observed.portalDistributionMatrix.cells,970);assert.equal(report.rootVerificationMatrixReadiness.observed.portalDistributionMatrix.gap,478);assert.equal(report.rootVerificationMatrixReadiness.observed.portalDistributionMatrix.notEvaluated,291);assert.equal(report.rootVerificationMatrixReadiness.boundary.authorityAtomicBehaviorDenominatorAvailable,false);assert.equal(report.rootVerificationMatrixReadiness.boundary.portalDistributionMatrixIsCoreSubjectArtifact,false);assert.equal(report.rootVerificationMatrixReadiness.boundary.runtimeSubstitution,false);assert.equal(report.rootVerificationMatrixReadiness.boundary.autoCreate,false);assert.equal(report.rootVerificationMatrixReadiness.boundary.completionEffect,'none');
});

test('Portal root Definitive lockは正式Coreと実commandを固定する',()=>{
  assert.equal(lock.coreCommit,'072d7ca77981f51754e824d70c6d4ecd55ea67e5');assert.equal(lock.command,'atlas audit <portal-root> --gate definitive');assert.equal(lock.expectedExitCode,1);assert.equal(lock.expectedDiagnosticSuffix,'を読み込めません');assert.equal(lock.failureOrdering,'core-order-independent');assert.equal(lock.knownMissingArtifacts.length,5);assert.equal(lock.portalInfrastructureSurfaceInventory.expectedMasterySurfaceIds.length,14);assert.equal(lock.portalInfrastructureSurfaceInventory.expectedCoverageTargetIds.length,14);
});

test('Portal固有Surface Inventoryは実Mastery/Target分母を縮小せず保持する',async()=>{
  const result=await validatePortalRootSurfaceInventory(root,surfaceInventory,lock);
  assert.equal(result.ok,true,result.errors.join(', '));assert.deepEqual(result.summary,{masterySurfaces:14,coverageTargets:14,inventedEdges:0});
  assert.equal(surfaceInventory.mapping.status,'not-declared-in-v1-contract');assert.equal(surfaceInventory.boundary.coreSubjectArtifactStatus,'missing');assert.equal(surfaceInventory.boundary.subjectDefinitiveEffect,'none');assert.equal(surfaceInventory.boundary.completionEffect,'none');assert.equal(surfaceInventory.boundary.autoPromotion,false);
});

test('Portal固有Surface Inventoryの分母縮小・edge捏造・完成格上げを拒否する',async()=>{
  const fixture=JSON.parse(await readFile(path.join(root,'fixtures/portal-root-surface-inventory/negative-cases.json'),'utf8'));
  assert.equal(fixture.cases.length,4);
  for(const item of fixture.cases){const result=await validatePortalRootSurfaceInventory(root,applyPortalRootSurfaceNegative(surfaceInventory,item),lock);assert.equal(result.ok,false,item.caseId);assert.ok(result.errors.includes(item.expectedDiagnostic),`${item.caseId}: ${result.errors.join(', ')}`);}
});
