import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import os from 'node:os';
import { applyPortalRootArtifactGapNegative, buildPortalRootArtifactGapIndex, ROOT_ARTIFACT_REQUIREMENTS, validatePortalRootArtifactGapIndex } from '../scripts/lib/portal-root-artifact-gap-index.mjs';
import { resolveCoreCheckout } from '../scripts/lib/core-checkout.mjs';

const root=process.cwd();const document=JSON.parse(await readFile(path.join(root,'evidence/portal-root-artifact-gap-index.json'),'utf8'));const schema=JSON.parse(await readFile(path.join(root,'contracts/schemas/portal-root-artifact-gap-index.schema.json'),'utf8'));const fixture=JSON.parse(await readFile(path.join(root,'fixtures/portal-root-artifact-gap-index/negative-cases.json'),'utf8'));

test('Portal rootの6 Core v2 artifact状態を固定Schema/Validatorへ結ぶ',async()=>{const result=await validatePortalRootArtifactGapIndex(root,document,schema);assert.equal(result.ok,true,result.errors.join(', '));assert.deepEqual(document.gaps.map((gap)=>gap.artifactPath),ROOT_ARTIFACT_REQUIREMENTS.map((item)=>item.artifactPath));assert.deepEqual(result.summary,{requiredArtifacts:6,missingArtifacts:5,presentArtifacts:1,openGaps:5,closedGaps:1});assert.equal(document.boundary.portalIsSubject,false);assert.equal(document.boundary.rootDefinitiveStatus,'root-definitive-incomplete');assert.equal(document.boundary.distributionStatus,'not-established');const verificationGap=document.gaps.find((item)=>item.artifactPath==='verification.matrix.yaml');assert.equal(verificationGap.status,'present');assert.equal(verificationGap.observed.exists,true);});

test('artifactが一部presentでもdenominatorと境界を維持したまま正直に集計する',async()=>{const {coreDir,expectedCommit}=resolveCoreCheckout(root,'072d7ca77981f51754e824d70c6d4ecd55ea67e5');const temporary=await mkdtemp(path.join(os.tmpdir(),'portal-root-gap-'));try{await mkdir(path.join(temporary,'evidence'),{recursive:true});await writeFile(path.join(temporary,'verification.matrix.yaml'),'schemaVersion: 1\n');const partial=await buildPortalRootArtifactGapIndex(temporary,coreDir,expectedCommit);const result=await validatePortalRootArtifactGapIndex(temporary,partial,schema,{coreDir,coreCommit:expectedCommit});assert.equal(result.ok,true,result.errors.join(', '));assert.equal(partial.status,'open');assert.deepEqual(partial.summary,{requiredArtifacts:6,missingArtifacts:5,presentArtifacts:1,openGaps:5,closedGaps:1});const verificationGap=partial.gaps.find((item)=>item.artifactPath==='verification.matrix.yaml');assert.equal(verificationGap.status,'present');assert.equal(verificationGap.observed.exists,true);const missingGap=partial.gaps.find((item)=>item.artifactPath==='definitive.yaml');assert.equal(missingGap.status,'missing');assert.equal(missingGap.observed.exists,false);}finally{await rm(temporary,{recursive:true,force:true});}});

test('欠落削除・phantom present・Core契約付替え・digest closure・summary偽装・Portal Subject化を拒否する',async()=>{assert.equal(fixture.cases.length,7);for(const item of fixture.cases){const result=await validatePortalRootArtifactGapIndex(root,applyPortalRootArtifactGapNegative(document,item),schema);assert.equal(result.ok,false,item.caseId);assert.ok(result.errors.includes(item.expectedDiagnostic),`${item.caseId}: ${result.errors.join(', ')}`);}});
