import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

const root=process.cwd();
test('Security Headerが主要境界を拒否する',async()=>{const headers=await readFile(path.join(root,'public/_headers'),'utf8');for(const token of ["default-src 'self'","object-src 'none'","frame-ancestors 'none'","Referrer-Policy: no-referrer","Permissions-Policy:"])assert.match(headers,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});
test('Fallback fixtureが除外・実行困難・失効を保持する',async()=>{const fixture=JSON.parse(await readFile(path.join(root,'fixtures/failure-scenarios.json'),'utf8'));const states=new Set(fixture.scenarios.map((item)=>item.state));for(const state of ['excluded','infeasible','expired'])assert.ok(states.has(state));});
test('Runtime Indexは固定Releaseまたは観測署名付きclean commitだけを宣言する',async()=>{const index=JSON.parse(await readFile(path.join(root,'app/data/index.generated.json'),'utf8'));assert.equal(index.sourcePolicy,'fixed-release-or-attested-clean-commit-only');assert.equal(index.fixedCommitAuditSummary.releaseEligible,0);assert.equal(index.subjects.length,97);});
test('CatalogのCore v1正本SHAとTrust分類をIndexから失わない',async()=>{const index=JSON.parse(await readFile(path.join(root,'app/data/index.generated.json'),'utf8'));assert.match(index.catalog.canonical.commit,/^[a-f0-9]{40}$/);assert.equal(index.catalog.canonical.policyVersion,'1.0.0');assert.equal(index.catalog.trust.usage,'fixture-only');});
test('Subject Definitive完成はv1 statusやCertificateから自動昇格しない',async()=>{const index=JSON.parse(await readFile(path.join(root,'app/data/index.generated.json'),'utf8'));assert.equal(index.completionPolicy.definitiveGate,'core-v2-final-fail-closed');assert.equal(index.completionPolicy.coreCommit,'072d7ca77981f51754e824d70c6d4ecd55ea67e5');assert.equal(index.completionPolicy.autoPromotion,false);assert.equal(index.subjects.filter((item)=>item.release?.completion.definitive).length,0);assert.deepEqual(index.definitiveV2Summary,{coreCommit:index.completionPolicy.coreCommit,contractStatus:'final',subjects:97,available:0,definitive:0,incomplete:0,missing:97,inventoryUnevaluated:97,openRequiredKnown:119,excluded:0,infeasible:3,runtimeProfiles:9,runtimeProfilesCurrent:0,runtimeProfilesUnverified:9,gapInstances:388,gapCounts:[{id:'core-gate:definitive',count:97},{id:'definitive.yaml',count:97},{id:'evidence/definitive-certificate.json',count:97},{id:'migrations/definitive-v2.yaml',count:97}],autoPromotion:false});});
test('UIはbounded履歴とSubject Definitiveを明示的に分離する',async()=>{const page=await readFile(path.join(root,'app/page.tsx'),'utf8');for(const label of ['bounded / epoch完了（履歴）','Subject Definitive完成','Subject Definitive未証明','Authority-derived inventory closure','Evidence観測Profile'])assert.ok(page.includes(label));});
test('未完了と非後退結果をUIから隠さない',async()=>{const page=await readFile(path.join(root,'app/page.tsx'),'utf8');for(const label of ['open required Targets','unclassified / 未完了','Non-regression','Failure visibility baseline','全件表示します'])assert.ok(page.includes(label));assert.ok(!page.includes('detail.evidence.slice('));});
test('Definitive v2欠落を全Subjectでfail-closed表示する',async()=>{const index=JSON.parse(await readFile(path.join(root,'app/data/index.generated.json'),'utf8'));assert.equal(index.subjects.length,97);for(const subject of index.subjects){assert.equal(subject.definitiveV2.status,'subject-definitive-input-missing');assert.equal(subject.definitiveV2.coreGate.result,'not-run');assert.equal(subject.definitiveV2.readOnly,true);assert.equal(subject.definitiveV2.autoPromotion,false);assert.ok(subject.definitiveV2.gapIds.length>=4);}});
