#!/usr/bin/env node
import { createPublicKey } from 'node:crypto';
import { execFileSync, spawnSync } from 'node:child_process';
import { readFile, readdir, stat } from 'node:fs/promises';
import path from 'node:path';
import { parse } from 'yaml';
import { schemaValidators, validateRelease } from './lib/validate.mjs';
import { evaluateNonRegression } from './lib/non-regression.mjs';
import { sha256, verifyDigest } from './lib/crypto.mjs';

const root=process.cwd();const errors=[];const checks=[];const ok=(name,condition,detail='')=>{checks.push({name,pass:Boolean(condition),detail});if(!condition)errors.push(`${name}: ${detail}`);};const read=(file,encoding)=>readFile(path.join(root,file),encoding);const yaml=async(file)=>parse(await read(file,'utf8'));
const [atlas,mastery,coverage,sources,skillPackage]=await Promise.all(['atlas.yaml','mastery.yaml','coverage.yaml','sources.lock.yaml','skill.package.yaml'].map(yaml));
const evidenceNames=(await readdir(path.join(root,'evidence'))).filter((name)=>/\.evidence\.json$/.test(name)).sort();const evidence=[];for(const name of evidenceNames)evidence.push(JSON.parse(await readFile(path.join(root,'evidence',name),'utf8')));
const certificate=JSON.parse(await read('evidence/completion-certificate.json','utf8'));const validators=await schemaValidators(path.join(root,'contracts/schemas'));const contract=validateRelease({atlas,mastery,coverage,sources,skillPackage,evidence,certificate},validators,{atlasId:atlas.id,version:skillPackage.atlas_release});ok('Core Schemaと横断契約',contract.ok,contract.errors.join('; '));
const claimNames=(await readdir(path.join(root,'claims'))).filter((name)=>/\.claim\.(json|ya?ml)$/.test(name));for(const name of claimNames){const claim=JSON.parse(await readFile(path.join(root,'claims',name),'utf8'));ok(`Claim Schema ${claim.id}`,validators.claim(claim),JSON.stringify(validators.claim.errors??[]));}
const provenance=await yaml('provenance.yaml');ok('Provenance Schema',validators.provenance(provenance),JSON.stringify(validators.provenance.errors??[]));const coreEval=JSON.parse(await read('evals/router.skill-eval.json','utf8'));ok('Skill Eval Schema',validators['skill-eval'](coreEval),JSON.stringify(validators['skill-eval'].errors??[]));const thirdParty=await yaml('third_party/manifest.yaml');ok('Third Party Schema',validators['third-party'](thirdParty),JSON.stringify(validators['third-party'].errors??[]));
ok('Authority Lock digest',coverage.authority_lock_digest===sha256(await read('sources.lock.yaml')),`expected=${coverage.authority_lock_digest}`);
const openRequired=coverage.targets.filter((target)=>target.requirement==='required'&&!['covered','excluded','infeasible'].includes(target.state));ok('Required Coverage closure',openRequired.length===0,`${openRequired.length} open`);
const evidenceIds=new Set(evidence.map((item)=>item.id));ok('Evidence参照',coverage.targets.every((target)=>target.evidence_ids.every((id)=>evidenceIds.has(id))),'covered TargetのEvidence実体');
for(const item of evidence){const artifactPath=path.join(root,item.artifact.uri);let bytes=null;try{bytes=await readFile(artifactPath);}catch{}ok(`Evidence artifact ${item.id}`,Boolean(bytes)&&sha256(bytes)===item.artifact.digest&&bytes.length===item.artifact.size_bytes,item.artifact.uri);}
const evalReport=JSON.parse(await read('evidence/reports/router-eval.json','utf8'));ok('Router Skill Eval',evalReport.verdict==='pass'&&evalReport.passRate>=skillPackage.evals.minimum_pass_rate&&evalReport.safetyCriticalPass,'安全系100%かつ全体90%以上');
const performance=JSON.parse(await read('evidence/reports/performance.json','utf8'));ok('Performance Budget',performance.verdict==='pass',JSON.stringify(performance.metrics));
const index=JSON.parse(await read('app/data/index.generated.json','utf8'));ok('97 Subject fixture',index.subjects.length===97,`${index.subjects.length} subjects`);ok('Source dependency boundary',index.sourcePolicy==='fixed-release-only','固定Releaseのみ');ok('Definitive auto-promotion拒否',index.completionPolicy?.definitiveGate==='pending-core-v2'&&index.completionPolicy?.autoPromotion===false,'Core v2確定までfail closed');const v1Promotions=index.subjects.flatMap((subject)=>subject.releaseHistory??[]).filter((release)=>release.completion?.certificateSchemaVersion===1&&release.completion?.definitive);ok('v1 Certificate bounded履歴',v1Promotions.length===0,`${v1Promotions.length} invalid promotions`);const brokenHistory=index.subjects.filter((subject)=>subject.release&&(subject.currentReleaseDigest!==subject.release.digest||!(subject.releaseHistory??[]).some((release)=>release.digest===subject.currentReleaseDigest)));ok('Release履歴とcurrent pointer',brokenHistory.length===0,`${brokenHistory.length} broken subjects`);
const nonRegression=await evaluateNonRegression(root);const recordedNonRegression=JSON.parse(await read('evidence/non-regression-report.json','utf8'));ok('非後退Baseline',nonRegression.verdict==='pass',`${nonRegression.summary.violations} violations`);ok('非後退結果の再現一致',sha256(`${JSON.stringify(nonRegression,null,2)}\n`)===sha256(`${JSON.stringify(recordedNonRegression,null,2)}\n`),nonRegression.baselineDigest);ok('未完了状態の明示',nonRegression.summary.openRequired===index.completionSummary.openRequired&&nonRegression.summary.unclassified===index.completionSummary.unclassified,`${nonRegression.summary.openRequired} open required / ${nonRegression.summary.unclassified} unclassified`);
const failureScenarios=JSON.parse(await read('fixtures/failure-scenarios.json','utf8'));for(const state of ['excluded','infeasible','expired'])ok(`Fallback fixture ${state}`,failureScenarios.scenarios.some((item)=>item.state===state),state);
const sbom=JSON.parse(await read('sbom.spdx.json','utf8'));const npmSbom=JSON.parse(await read('sbom.npm.spdx.json','utf8'));const unknown=npmSbom.packages.filter((item)=>item.licenseDeclared==='NOASSERTION');ok('SPDX Release SBOM',sbom.spdxVersion==='SPDX-2.3'&&sbom.packages.length>0,'Core Release package');ok('SPDX npm SBOM',npmSbom.spdxVersion==='SPDX-2.3'&&npmSbom.packages.length>0&&unknown.length===0,`${npmSbom.packages.length} packages / unknown licenses=${unknown.length}`);
for(const required of ['README.md','LICENSE','NOTICE','SECURITY.md','third_party/manifest.yaml','sbom.spdx.json','sbom.npm.spdx.json','provenance.yaml','contracts/non-regression-baseline.json','contracts/non-regression-mappings.json','.agents/skills/technology-atlas-router/SKILL.md','evals/router.skill-eval.json','evidence/non-regression-report.json','evidence/non-regression-harness.json','evidence/non-regression.evidence.json','evidence/completion-certificate.json','release/manifest.json','public/_headers']){let exists=false;try{exists=(await stat(path.join(root,required))).isFile();}catch{}ok(`必須成果物 ${required}`,exists,required);}
ok('Completion Certificate Schema',validators['completion-certificate'](certificate),JSON.stringify(validators['completion-certificate'].errors??[]));const {signature,...certificatePayload}=certificate;ok('Completion Certificate payload digest',sha256(certificatePayload)===signature.digest,signature.digest);ok('Certificate Evidence Set',certificate.required_profiles.every((item)=>item.result==='pass')&&certificate.skill_eval.pass_rate>=.9,'local pass / skill eval');
const publicKey=createPublicKey(await read('release/public-key.pem','utf8'));
const releaseEnvelope=JSON.parse(await read('release/manifest.json','utf8'));ok('Portal Release digest',sha256(releaseEnvelope.payload)===releaseEnvelope.release.digest,releaseEnvelope.release.digest);ok('Portal Release signature',verifyDigest(releaseEnvelope.release.digest,releaseEnvelope.signature.value,publicKey),releaseEnvelope.signature.keyId);
const sourceFiles=['app/page.tsx','app/layout.tsx','app/globals.css','scripts/import-releases.mjs','.agents/skills/technology-atlas-router/SKILL.md'];let combined='';for(const file of sourceFiles)combined+=await read(file,'utf8');ok('External script / telemetry',!/(google-analytics|gtag\(|segment\.io|mixpanel|<script[^>]+https?:)/i.test(combined),'外部追跡なし');ok('秘密鍵非同梱',!combined.includes('BEGIN PRIVATE KEY'),'private key materialなし');
let commits=[];try{commits=execFileSync('git',['rev-list','HEAD'],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(Boolean);}catch{}const unsigned=commits.filter((commit)=>!execFileSync('git',['show','-s','--format=%(trailers:key=Signed-off-by,valueonly)',commit],{cwd:root,encoding:'utf8'}).trim());ok('DCO Signed-off-by',commits.length>0&&unsigned.length===0,`${commits.length-unsigned.length}/${commits.length} commits`);const certificateCommitExists=spawnSync('git',['cat-file','-e',`${certificate.commit}^{commit}`],{cwd:root}).status===0;const certificateCommitIsAncestor=certificateCommitExists&&spawnSync('git',['merge-base','--is-ancestor',certificate.commit,'HEAD'],{cwd:root}).status===0;ok('Certificate source commit',certificateCommitExists&&certificateCommitIsAncestor,certificate.commit);
let postCertificateChanges=[];if(certificateCommitIsAncestor)postCertificateChanges=execFileSync('git',['diff','--name-only',`${certificate.commit}..HEAD`],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(Boolean);const derivedAttachments=new Set(['evidence/completion-certificate.json','release/manifest.json']);const staleSourceChanges=postCertificateChanges.filter((file)=>!derivedAttachments.has(file));ok('Certificate freshness scope',certificateCommitIsAncestor&&staleSourceChanges.length===0,staleSourceChanges.join(', ')||'derived attachments only');
console.log(`Publication Gate: ${checks.filter((item)=>item.pass).length}/${checks.length} checks`);for(const check of checks)console.log(`${check.pass?'PASS':'FAIL'} ${check.name}${check.detail?` — ${check.detail}`:''}`);if(errors.length){console.error(`\nPublication拒否: ${errors.length}件`);process.exitCode=1;}
